name: Unity Windows IL2CPP Build

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string
      versioning:
        required: true
        type: string
      version:
        required: false
        type: string

jobs:
  build-windows:
    name: Build StandaloneWindows64
    runs-on: windows-2019
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ inputs.checkout-ref }}
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        id: build-0
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
        continue-on-error: true
      # Build Retry (temp workaround for https://github.com/game-ci/unity-builder/issues/569)
      - name: Retry Build
        if: ${{ steps.build-0.outcome == 'failure' }}
        id: build-1
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
          versioning: ${{ inputs.versioning }}
          version: ${{ inputs.version }}
      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build